using System;

public enum TAG_STEP
{
    BEGIN_DRAW = 3,
    BEGIN_FIRST = 1,
    BEGIN_MULLIGAN = 4,
    BEGIN_SHUFFLE = 2,
    FINAL_GAMEOVER = 15,
    FINAL_WRAPUP = 14,
    MAIN_ACTION = 10,
    MAIN_BEGIN = 5,
    MAIN_CLEANUP = 0x10,
    MAIN_COMBAT = 11,
    MAIN_DRAW = 8,
    MAIN_END = 12,
    MAIN_NEXT = 13,
    MAIN_READY = 6,
    MAIN_RESOURCE = 7,
    MAIN_START = 9,
    MAIN_START_TRIGGERS = 0x11
}

